Repository Enactus-Trieste/android-app-borghi, pull requests merged in 2023-05, with the labels that each got.

#50 Bug solved
  app/src/main/java/it/units/borghisegreti/activities/MainActivity.java
  app/src/main/java/it/units/borghisegreti/fragments/MapsFragment.java
Labels: bug

#51 Added tests for `RegistrationFragment`
  .firebaserc
  .gitignore
  .idea/androidTestResultsUserPreferences.xml
  app/src/androidTest/java/it/units/borghisegreti/RegistrationFragmentValidationTests.java
  app/src/debug/ic_launcher-playstore.png
  app/src/main/ic_remote_working_logo-playstore.png
  app/src/main/java/it/units/borghisegreti/fragments/MapsFragment.java
  app/src/main/java/it/units/borghisegreti/viewmodels/MapViewModel.java
  app/src/main/res/layout/fragment_registration.xml
  app/src/test/java/it/units/borghisegreti/ExampleUnitTest.java
  database.rules.json
  firebase.json
Labels: enhancement

#55 6 translation of the issues and the current documentation readmemd
  README.md
Labels: documentation

#57 Added new theme
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
Labels: duplicate, enhancement

#58 Userprofile fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/it/units/borghisegreti/activities/MainActivity.java
  app/src/main/java/it/units/borghisegreti/fragments/UserProfileFragment.java
  app/src/main/java/it/units/borghisegreti/utils/Database.java
  app/src/main/java/it/units/borghisegreti/viewmodels/UserProfileViewModel.java
  app/src/main/res/drawable/account_circle.xml
  app/src/main/res/drawable/done.xml
  app/src/main/res/drawable/help.xml
  app/src/main/res/drawable/legal_terms.xml
  app/src/main/res/drawable/settings.xml
  app/src/main/res/font/inter.xml
  app/src/main/res/font/inter_bold.xml
  app/src/main/res/font/inter_extrabold.xml
  app/src/main/res/font/inter_semibold.xml
  app/src/main/res/font/pt_sans.xml
  app/src/main/res/font/pt_sans_bold.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#66 Completed activities fragment and other general improvements
  app/src/main/assets/markers/TaipanaIcon.png
  app/src/main/java/it/units/borghisegreti/activities/MainActivity.java
  app/src/main/java/it/units/borghisegreti/adapters/ExperienceViewHolder.java
  app/src/main/java/it/units/borghisegreti/fragments/ExperiencesFragment.java
  app/src/main/java/it/units/borghisegreti/fragments/MapsFragment.java
  app/src/main/res/drawable/activity_points_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/completed_experience.xml
  app/src/main/res/layout/fragment_experiences.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#68 Added placeholder images
  app/src/main/assets/images/nature_alps.jpg
  app/src/main/assets/images/nature_horse.jpg
  app/src/main/assets/images/restaurant_table.jpg
  app/src/main/java/it/units/borghisegreti/adapters/CarouselAdapter.java
  app/src/main/java/it/units/borghisegreti/adapters/CarouselItem.java
  app/src/main/java/it/units/borghisegreti/adapters/CarouselItemViewHolder.java
  app/src/main/java/it/units/borghisegreti/fragments/dialogs/ExperienceDialog.java
  app/src/main/res/layout/experience_dialog_carousel.xml
  app/src/main/res/layout/fragment_experience_dialog.xml
  app/src/main/res/values-it-rIT/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
